### ISSUE TITLE
Keep packagedocs example?

### ISSUE THREAD

**Issue by pat-s** [krlmlr/tic.packagedocs#1]
Or drop it? I do not know anyone how uses _packagedocs_. 

The package hasn't been updated in 2 years.

**Comment by krlmlr** [comment]
We want to show that we support various use cases. Do we need to move it down in the list of examples?

**Comment by pat-s** [comment]
> We want to show that we support various use cases. Do we need to move it down in the list of examples?

Ok, sounds reasonable. I'll move it down.
